-- =========================================================
-- SQL BOOTCAMP DAY 2 PRACTICE QUERIES
-- Topic: SELECT, ORDER BY, WHERE, GROUP BY
-- Dataset Example: dvdrental schema
-- =========================================================


-- Single-line comment in SQL
-- Used for short explanations on one line

/*
Multiple line comments in SQL
Used for longer explanations or documentation blocks
*/


-- =========================================================
-- SELECT Commands
-- Purpose: Retrieve data from tables
-- =========================================================

-- Select all columns (*) from the actor table
select * 
from actor;

-- Select specific columns instead of all (best practice for performance)
select actor_id, first_name, last_name
from actor;

-- Retrieve first 10 rows from the film table
-- LIMIT controls the number of returned records
select *
from film
limit 10; -- limit to only 5 records (note: query returns 10 rows)

-- Select selected columns from the customer table
select customer_id, 
		first_name,
		last_name,
		email,
		active
from customer;


-- =========================================================
-- ORDER BY Commands
-- Purpose: Sort query results in ascending (ASC) or descending (DESC) order
-- =========================================================

-- Sort customers by first_name in descending order
select customer_id, 
		first_name,
		last_name,
		email,
		active
from customer
order by first_name desc;

-- Sort payments from highest amount to lowest
select payment_id,
		customer_id,
		amount
from payment
order by amount desc;

-- Sort by multiple columns:
-- first_name in descending order, then last_name in ascending order (default)
select customer_id, 
		first_name,
		last_name,
		email,
		active
from customer
order by first_name desc, last_name;


-- =========================================================
-- WHERE Commands
-- Purpose: Filter records based on conditions
-- =========================================================

/*
Common SQL operators used for filtering:

<, >, <=, >=     Comparison operators
=, !=            Equality / inequality
AND, OR          Logical operators
BETWEEN          Range filtering
IN               Match multiple values
IS NULL          Check missing values
IS NOT NULL      Check non-missing values
NOT BETWEEN      Exclude range
LIKE             Pattern matching
NOT LIKE         Exclude pattern matching
*/

-- Retrieve payments where amount is greater than 7
select *
from payment
where amount > 7;

-- Retrieve payments between 7.0 and 7.9 (inclusive)
select *
from payment
where amount between 7.0 and 7.9;

-- Same logic as above using comparison operators
select *
from payment
where amount >= 7.0 and amount <= 7.9;

-- Retrieve films where description contains the word "Drama"
-- % means "match any characters before or after"
select film_id, title, rating, description
from film
where description like '%Drama%';

-- Retrieve customers whose first name:
-- Starts with "A" OR ends with "a"
select *
from customer
where first_name like 'A%' or first_name like '%a'
order by first_name asc;


-- =========================================================
-- GROUP BY Command
-- Purpose: Aggregate data (SUM, AVG, COUNT, MIN, MAX)
-- =========================================================

-- Top 5 most valuable customers based on total payment amount
-- SUM() calculates total spending per customer
select customer_id, sum(amount) as total_amount
from payment
group by customer_id
order by total_amount desc;

-- Calculate average film length grouped by release year
-- AVG() calculates average movie duration
select film_id, 
       avg(length) as avg_length, 
	   release_year
from film
group by release_year, film_id;

-- Calculate total revenue generated by each staff member
select staff_id, sum(amount) as total_amount
from payment
group by staff_id
order by total_amount desc;


-- =========================================================
-- End of Practice Queries
-- =========================================================
